/*
 * This file has been automatically generated by the WICED Smart Designer.
 * BLE device's GATT database, device configuration, function that can be used
 * to send notifications and indications.
 *
 */

// DoorDoorBeacon1_db.c

#include "bleprofile.h"
#include "bleapp.h"
#include "gpiodriver.h"
#include "string.h"
#include "stdio.h"
#include "platform.h"
#include "DoorDoorBeacon1_db.h"

const UINT8 gatt_database[]= // Define GATT database
{
// ***** Primary service 'Generic Access'
    //<Name>Generic Access</Name>
    //<Uuid>1800</Uuid>
    //Service handle: HDLS_GENERIC_ACCESS
    //Service UUID: UUID_SERVICE_GAP
    PRIMARY_SERVICE_UUID16 (HDLS_GENERIC_ACCESS, UUID_SERVICE_GAP),

    //<Name>Device Name</Name>
    //<Uuid>2A00</Uuid>
    CHARACTERISTIC_UUID16 (HDLC_GENERIC_ACCESS_DEVICE_NAME,
                           HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE,
                           UUID_CHARACTERISTIC_DEVICE_NAME,
                           LEGATTDB_CHAR_PROP_READ,
                           LEGATTDB_PERM_READABLE,
                           8),
    'D','o','o','r','D','o','o','r',

    //<Name>Appearance</Name>
    //<Uuid>2A01</Uuid>
    CHARACTERISTIC_UUID16 (HDLC_GENERIC_ACCESS_APPEARANCE,
                           HDLC_GENERIC_ACCESS_APPEARANCE_VALUE,
                           UUID_CHARACTERISTIC_APPEARANCE,
                           LEGATTDB_CHAR_PROP_READ,
                           LEGATTDB_PERM_READABLE,
                           2),
    0x00,0x00,

// ***** Primary service 'Generic Attribute'
    //<Name>Generic Attribute</Name>
    //<Uuid>1801</Uuid>
    //Service handle: HDLS_GENERIC_ATTRIBUTE
    //Service UUID: UUID_SERVICE_GATT
    PRIMARY_SERVICE_UUID16 (HDLS_GENERIC_ATTRIBUTE, UUID_SERVICE_GATT),

// ***** Primary service 'DoorDoor'
    //<Name>DoorDoor</Name>
    //<Uuid>7c b1 8f 43 ff 7c 48 c9 8e de a2 13 1e 22 33 6b</Uuid>
    //Service handle: HDLS_DOORDOOR
    //Service UUID: __UUID_DOORDOOR
    PRIMARY_SERVICE_UUID128 (HDLS_DOORDOOR, __UUID_DOORDOOR),

    //<Name>Blink</Name>
    //<Uuid>64 b7 ce b6 58 51 4e 2b b1 19 49 59 ef 06 fa 75</Uuid>
    CHARACTERISTIC_UUID128_WRITABLE (HDLC_DOORDOOR_BLINK,
                           HDLC_DOORDOOR_BLINK_VALUE,
                           __UUID_DOORDOOR_BLINK,
                           LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE | LEGATTDB_CHAR_PROP_NOTIFY | LEGATTDB_CHAR_PROP_INDICATE,
                           LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ,
                           1),
    0x00,

    //<ClientConfiguration>
    //<Notification>false</Notification>
    //<Indication>false</Indication>
    CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_DOORDOOR_BLINK_CLIENT_CONFIGURATION,
                                     UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                                     LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_CMD | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_RELIABLE_WRITE | LEGATTDB_PERM_AUTH_WRITABLE,
                                     2),
    BIT16_TO_8 (CCC_NONE),

    //<Name>Button</Name>
    //<Uuid>f5 60 10 87 df 10 44 28 99 b9 ec 4c 4e bc 69 c3</Uuid>
    CHARACTERISTIC_UUID128 (HDLC_DOORDOOR_BUTTON,
                           HDLC_DOORDOOR_BUTTON_VALUE,
                           __UUID_DOORDOOR_BUTTON,
                           LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_INDICATE,
                           LEGATTDB_PERM_READABLE,
                           1),
    0x00,

    //<ClientConfiguration>
    //<Notification>false</Notification>
    //<Indication>false</Indication>
    CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_DOORDOOR_BUTTON_CLIENT_CONFIGURATION,
                                     UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                                     LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_CMD | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_RELIABLE_WRITE | LEGATTDB_PERM_AUTH_WRITABLE,
                                     2),
    BIT16_TO_8 (CCC_NONE),

};
// Indication sent, waiting for ack
UINT8 doordoorbeacon1_indication_sent = 0;
// Length of the GATT database
const UINT16 gatt_database_len = sizeof(gatt_database);
// Pointer to the bonded peer info or NULL if not bonded
__HOSTINFO *p_bonded = NULL;
// Following structure defines GPIO configuration used by the application
const BLE_PROFILE_GPIO_CFG doordoorbeacon1_gpio_cfg =
{
    {
        GPIO_PIN_WP,                               // This need to be used to enable/disable NVRAM write protect
        GPIO_PIN_LED_IO25, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 // Other GPIOs are not used
    },
    /*.gpio_flag =*/
    {
        GPIO_SETTINGS_WP,
        GPIO_SETTINGS_LED, 0, 0, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
    }
};

// Main vendor specific service
UINT8 doordoorbeacon1_uuid_main_vsc_service[16] = {__UUID_DOORDOOR};
// Indication confirmation callback
static void __indication_cfm()
{
    doordoorbeacon1_indication_sent = 0;
    doordoorbeacon1_indication_cfm();
}

// Registers timer. Should be called from doordoorbeacon1_create()
void doordoorbeacon1_reg_timer()
{
}

// Finds bonded peer in the hostinfo. On exit p_bonded points on bonded peer or NULL
__HOSTINFO *__find_bonded_peer(UINT8 *bda)
{
    int i;
    p_bonded = NULL;
    if (0 == memcmp(bda, p_hostinfo_generated->bdaddr, 6))
    {
        p_bonded = p_hostinfo_generated;
    }
    return p_bonded;
}

// initializes persistent values in the hostinfo to add bonded peer
void doordoorbeacon1_add_bond(UINT8 *bda)
{
    // Find this peer among bonded peers in the p_hostinfo_generated
    if (!__find_bonded_peer(bda))
    {
        // Peer is not found. Remember new one.
        p_bonded = p_hostinfo_generated;
        memcpy(p_bonded->bdaddr, bda, 6);
    }

    // Clear persistent generated values in the hostinfo for just bonded peer

    // Set the initial value of the client configuration descriptor for value 'Blink'
    p_bonded->doordoor_blink_client_configuration = 0;

    // Set the initial value of the client configuration descriptor for value 'Button'
    p_bonded->doordoor_button_client_configuration = 0;
}

// Prepares generated code for connection - writes persistent values from __HOSTINFO to GATT DB
void __on_connection_up()
{
    doordoorbeacon1_indication_sent = 0;
    // Find this peer among bonded peers in the p_hostinfo_generated
    if (__find_bonded_peer(doordoorbeacon1_remote_addr))
    {
        BLEPROFILE_DB_PDU db_pdu;

        // Write the value of the client configuration descriptor for value 'Blink'
        db_pdu.len = 2;
        db_pdu.pdu[0] = p_bonded->doordoor_blink_client_configuration & 0xff;
        db_pdu.pdu[1] = (p_bonded->doordoor_blink_client_configuration >> 8) & 0xff;
        bleprofile_WriteHandle(HDLD_DOORDOOR_BLINK_CLIENT_CONFIGURATION, &db_pdu);

        // Write the value of the client configuration descriptor for value 'Button'
        db_pdu.len = 2;
        db_pdu.pdu[0] = p_bonded->doordoor_button_client_configuration & 0xff;
        db_pdu.pdu[1] = (p_bonded->doordoor_button_client_configuration >> 8) & 0xff;
        bleprofile_WriteHandle(HDLD_DOORDOOR_BUTTON_CLIENT_CONFIGURATION, &db_pdu);
    }
}

// Updates __HOSTINFO by the value written by peer.
// Returns true if any persistent value is changed
BOOL __write_handler(UINT16 handle, int len, UINT8 *attrPtr)
{
    BOOL res = FALSE;
    if (handle == HDLC_DOORDOOR_BLINK_VALUE)
    {
        if (len > 1)
        {
            ble_trace2("bad length:%d handle:%04x\n", len, handle);
        }
        else
        {
            //call custom on_write function
            ble_trace1("write handle:%04x\n", handle);
            res = on_write_doordoor_blink(len, attrPtr);
        }
    }
    if ((len == 2) && (handle == HDLD_DOORDOOR_BLINK_CLIENT_CONFIGURATION))
    {
        // find this peer among bonded peers in the p_hostinfo_generated
        if (__find_bonded_peer(doordoorbeacon1_remote_addr))
        {
            p_bonded->doordoor_blink_client_configuration = attrPtr[0] + (attrPtr[1] << 8);
            ble_trace2("handle:%02x val:%04x\n", handle, p_bonded->doordoor_blink_client_configuration);
            res = TRUE;
        }
    }
    if ((len == 2) && (handle == HDLD_DOORDOOR_BUTTON_CLIENT_CONFIGURATION))
    {
        // find this peer among bonded peers in the p_hostinfo_generated
        if (__find_bonded_peer(doordoorbeacon1_remote_addr))
        {
            p_bonded->doordoor_button_client_configuration = attrPtr[0] + (attrPtr[1] << 8);
            ble_trace2("handle:%02x val:%04x\n", handle, p_bonded->doordoor_button_client_configuration);
            res = TRUE;
        }
    }
    return res;
}

// It should be called when 'Device Name' is changed.
BOOL store_in_db_generic_access_device_name(UINT8* p_value, UINT8 value_len)
{
    BLEPROFILE_DB_PDU db_pdu;
    // Write value to the GATT DB
    ble_trace2("write len:%d handle:%02x\n", value_len, HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE);
    memcpy(&db_pdu.pdu[0], p_value, value_len);
    db_pdu.len = value_len;
    bleprofile_WriteHandle(HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE, &db_pdu);
    return TRUE;
}

// It should be called when 'Appearance' is changed.
BOOL store_in_db_generic_access_appearance(UINT8* p_value, UINT8 value_len)
{
    BLEPROFILE_DB_PDU db_pdu;
    // Write value to the GATT DB
    ble_trace2("write len:%d handle:%02x\n", value_len, HDLC_GENERIC_ACCESS_APPEARANCE_VALUE);
    memcpy(&db_pdu.pdu[0], p_value, value_len);
    db_pdu.len = value_len;
    bleprofile_WriteHandle(HDLC_GENERIC_ACCESS_APPEARANCE_VALUE, &db_pdu);
    return TRUE;
}

// It should be called when 'Blink' is changed.
BOOL store_in_db_doordoor_blink(UINT8* p_value, UINT8 value_len, BOOL write, BOOL notify)
{
    BLEPROFILE_DB_PDU db_pdu;
    //if write is requested
    if (write)
    {
        // Write value to the GATT DB
        ble_trace2("write len:%d handle:%02x\n", value_len, HDLC_DOORDOOR_BLINK_VALUE);
        memcpy(&db_pdu.pdu[0], p_value, value_len);
        db_pdu.len = value_len;
        bleprofile_WriteHandle(HDLC_DOORDOOR_BLINK_VALUE, &db_pdu);
    }
    // If notification is requested
    if (notify)
    {
        if (__find_bonded_peer(doordoorbeacon1_remote_addr))
        {
            // Exit if notify and indicate are not configured in the Client Configuration Descriptor
            if (0 == (p_bonded->doordoor_blink_client_configuration & (CCC_NOTIFICATION | CCC_INDICATION)))
            {
                ble_trace1("don't notify handle:%02x\n", HDLC_DOORDOOR_BLINK_VALUE);
                return TRUE;
            }
            // Just return FALSE if connection is down
            if (doordoorbeacon1_connection_handle == 0)
            {
                ble_trace1("not connected handle:%02x\n", HDLC_DOORDOOR_BLINK_VALUE);
                return FALSE;
            }
            // Just return FALSE if we are waiting for confirmation
            if (doordoorbeacon1_indication_sent != 0)
            {
                ble_trace1("wait confirmation handle:%02x\n", HDLC_DOORDOOR_BLINK_VALUE);
                return FALSE;
            }
            //if write is not requested then we did't write the value. Read it
            if (!write)
            {
                bleprofile_ReadHandle(HDLC_DOORDOOR_BLINK_VALUE, &db_pdu);
            }
            // Notify property is true. If client has registered for notification
            if (p_bonded->doordoor_blink_client_configuration & CCC_NOTIFICATION)
            {
                ble_trace2("notify len:%d handle:%02x\n", db_pdu.len, HDLC_DOORDOOR_BLINK_VALUE);
                bleprofile_sendNotification(HDLC_DOORDOOR_BLINK_VALUE, (UINT8 *)db_pdu.pdu, db_pdu.len);
            }
            // Indicate property is true. If client has registered for indication,
            // We can send only one and need to wait for ack.
            else
            {
                doordoorbeacon1_indication_sent = 1;
                ble_trace2("indicate len:%d handle=%02x\n", db_pdu.len, HDLC_DOORDOOR_BLINK_VALUE);
                bleprofile_sendIndication(HDLC_DOORDOOR_BLINK_VALUE, (UINT8 *)db_pdu.pdu, db_pdu.len, __indication_cfm);
            }
        }
    }
    return TRUE;
}

// It should be called when 'Button' is changed.
BOOL store_in_db_doordoor_button(UINT8* p_value, UINT8 value_len, BOOL write, BOOL notify)
{
    BLEPROFILE_DB_PDU db_pdu;
    //if write is requested
    if (write)
    {
        // Write value to the GATT DB
        ble_trace2("write len:%d handle:%02x\n", value_len, HDLC_DOORDOOR_BUTTON_VALUE);
        memcpy(&db_pdu.pdu[0], p_value, value_len);
        db_pdu.len = value_len;
        bleprofile_WriteHandle(HDLC_DOORDOOR_BUTTON_VALUE, &db_pdu);
    }
    // If notification is requested
    if (notify)
    {
        if (__find_bonded_peer(doordoorbeacon1_remote_addr))
        {
            // Exit if notify and indicate are not configured in the Client Configuration Descriptor
            if (0 == (p_bonded->doordoor_button_client_configuration & (CCC_NOTIFICATION | CCC_INDICATION)))
            {
                ble_trace1("don't notify handle:%02x\n", HDLC_DOORDOOR_BUTTON_VALUE);
                return TRUE;
            }

            // Just return FALSE if connection is down
            if (doordoorbeacon1_connection_handle == 0)
            {
                ble_trace1("not connected handle:%02x\n", HDLC_DOORDOOR_BUTTON_VALUE);
                return FALSE;
            }
            // Just return FALSE if we are waiting for confirmation
            if (doordoorbeacon1_indication_sent != 0)
            {
                ble_trace1("wait confirmation handle:%02x\n", HDLC_DOORDOOR_BUTTON_VALUE);
                return FALSE;
            }
            //if write is not requested then we did't write the value. Read it
            if (!write)
            {
                bleprofile_ReadHandle(HDLC_DOORDOOR_BUTTON_VALUE, &db_pdu);
            }
            // Notify property is true. If client has registered for notification
            if (p_bonded->doordoor_button_client_configuration & CCC_NOTIFICATION)
            {
                ble_trace2("notify len:%d handle:%02x\n", db_pdu.len, HDLC_DOORDOOR_BUTTON_VALUE);
                bleprofile_sendNotification(HDLC_DOORDOOR_BUTTON_VALUE, (UINT8 *)db_pdu.pdu, db_pdu.len);
            }
            // Indicate property is true. If client has registered for indication,
            // We can send only one and need to wait for ack.
            else
            {
                doordoorbeacon1_indication_sent = 1;
                ble_trace2("indicate len:%d handle=%02x\n", db_pdu.len, HDLC_DOORDOOR_BUTTON_VALUE);
                bleprofile_sendIndication(HDLC_DOORDOOR_BUTTON_VALUE, (UINT8 *)db_pdu.pdu, db_pdu.len, __indication_cfm);
            }
        }
    }
    return TRUE;
}

